# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/vault/

vault_mysql_root_password: 6OPQxEcNFhXKX1nHaIgY1ZxDLW878jEb1qe12z7DoJ3s6rsYPoTVC81dhhnbC98G
vault_wordpress_sites:
  chosen.bonsai.so:
    admin_password: DxgjmgwSZRslXXs4EELup6JnncErgvRCxhoHN8WYGeJxwKgHYdbB9xTAetf6Ya1N
    env:
      db_password: nU6X6hIUfB4cywuuKhvpn4mrYwhHkHNXtxpO1VRauKtIWsJhPlaRTAzD5PDo5ciw
      auth_key: kaiXbU81cfbX09NaBuNjCM5uvJaxvwdXJdHXBBEc2GBW65SnWqa6dGpDXuQg3FfH
      secure_auth_key: LvwdiMwaHDkqXiuE2V9T5YpGzzeXSR8XdbVyJ1OEAa19KNz5ci0StvCR5Y2FOmOh
      logged_in_key: 2UswgMPJuGdHuDOtoMnctuaa36RfvK2yHNatNnsNfDQcgVW3qtd2PeoU1QWkqNkH
      nonce_key: XXSaZKC7pEHwpwhbgKrTcnBYA2ruUfXzdv7aELWChMzHMSAjjxG3X5ekZmjfoaAk
      auth_salt: hniXV9u9ocClfBBdF5TA4H4x2kWmrzp5dqJarK4ZRjEFJllKxs5VfL9mAPRDDzlu
      secure_auth_salt: EDjlX8qGnhgsf9xpnyRjglNVTySsh76233gwV7QWd88eCV5zaZgLUYe8slXJfeR9
      logged_in_salt: PNXVWyuxRN5jy84mY2eMe0InKQ7JW6jXV0tiUtgugDdeeWWXhekrSENUcYrKP5kR
      nonce_salt: RQGFLjFRKdL8YJREH8lnWXGbvf7IfnRm8mRCkpUGaZwn3PmfaFQhqI7tA4rLokdN
