# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/vault/

vault_mysql_root_password: Rjf2hBpSZ7U8urGU8zQ8OvvyC7feDFb5XgTdKNibJ0aqgu3EWL5DAzakylTTPW5T
vault_users:
- name: '{{ admin_user }}'
  password: Ia3F8EWHn4xKZBl6dHvk3ouJ8alQVYnNDNbVDX4YiKBGgFCQEvmHwf7bzgKT7cps
  salt: HBd6Tks6UJICCGOcMOQpPv1PF1KDMYYMlRxBJDjc2CMAxKatVbbbbrSka7CgAfhi
vault_wordpress_sites:
  chosen.bonsai.so:
    admin_password: 5kFcqVnX37ftRtjJEAwcYnirbe5i2mP2o2MBTkzOwoq6dpFBWtXUiTujTf35or7m
    env:
      db_password: zDVlKrULaZNNjfVt3nBYKpT0wrgPWixENqQcc199uhTOWisWlGALceTay2D4Ojrw
      auth_key: rhPJ8wCB9JdXmLbeizkhLkBt2EkEF5iyoZWqfaZqcSvLrq89MiIqmpynxeG3KoNI
      secure_auth_key: oReoZs0i8aHm6g7OdaB4drkxCT3DJQKWeaggJuo1q0PQncyRdHNlMWMasvUa5Fdg
      logged_in_key: FEKe6kcfkR0q7bXBdO8KC3jFoIHankkzmauLj9ghhEGjb0fCJCpcdIVeGQGjpQzo
      nonce_key: 4EOi7H4VWMVmo08bSJUjpKAtfnPMJPwLOqBdYAvMdIZKuNV8KY2dScCdYFfRDbHu
      auth_salt: LXl1KotOK2Z6qxNa9bcTcpUCcxSNIGqtfjVHEjDeWETU9Upypc8GSyPiBgHNAiQi
      secure_auth_salt: ldvpiPrzW9UqVgif5Lf2yfTtXU5LDzy80hwNEpJQOZarcsJyrHGvoSCAAwmfl3fF
      logged_in_salt: FDkZd3grptGI2TS7xwjI7c5dVJnown6rlJAW5kOWFlXuykeFxi5e7QPHuWwjHqHS
      nonce_salt: RCwuy25oLxhzEoijnJ1HCKL5765O3zGSJ6eLEjSa5OP9u00NmLQdH2Qa33357FPI
