# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/vault/

vault_mysql_root_password: 3wGGScAiiHLidJ2zwPHCCPFEx0TdDb5WiblxZxzgHlbkdwKb10RBJxPgl5hekXiO
vault_users:
- name: '{{ admin_user }}'
  password: BxHEFX898SG58DIpFOWkc8aq39Zybl4rA4sAP4fWC6cihVfmReIx8XmKNZmucxOw
  salt: Ihvl5SiUaT1FyfXWp18ct3ITWhUOJMBvKqG3CJcEs8jmDS6YlhKaVKWjbP7ma8K1
vault_wordpress_sites:
  chosen.bonsai.so:
    admin_password: kuuTAb8DgPhJYL45ShIMuu9YCNzt47IDNn0xnmrnn0uJvo5dIkC8ag3sefqfwupC
    env:
      db_password: Nfuh0U9Vyqv3FPgF5HHniiVY6dd03KLQQv5z7U0vQ1cPifJNynHbEh1CvjF3ahoq
      auth_key: E18Tfj3dyKFi8QbZoqkhihhf5MXC8xT28YjuKwYzpWi4LV309usB5bumj7q54UvP
      secure_auth_key: Okc83nbS5xRhQUJta1DqkYcvepEqOclEnmYjxqkZaGXO2d5hECriMpBpXaJVJplS
      logged_in_key: 5sMm3lvtyP8XgKdmdU20blBSj7f8KYqaDegtW0uc8sd9cGu3mXxc4msX6McNgost
      nonce_key: 8Yw7NbKkTSR7DtczNBszLigX0YTGCyeGiCwbU3Vpvn8UASyXwrLHzktH2uYqUJOl
      auth_salt: kQrwCtYYaNXlaw0T6zOz5NHF0pfLEmzLia3izyFxsAsIZXidU2ygHQA3xcR9ubtm
      secure_auth_salt: IjiG3ea3TOya4bvltfLZIOFMIoka2r2IeR0ANEvauncD5Z6VHcogTfL09ZK5EGMI
      logged_in_salt: z6l9TOO443Vftnh71c5T8eS0hpSs6mYj5h1r7Djqwzj1caa8KRDC44Uktft1Jpo9
      nonce_salt: aYWIMUegHcVwY6RCkaIITyyQtoLEF3MA4z2ZIG3kx6kqGYCfQfU9Yxz78eTpQOCy
